assets/javascripts/initializers/extend-for-policy.js.es6
assets/stylesheets/common/discourse-policy.scss
plugin.rb

This PR cleans up the styles and fixes a few issues.
The major changes are:
1. improved icon alignment
2. adds a new icon for users who accepted the policy (`user-check` instead of just `user`)
3. moves the user count to the left of the icon (matches what we do with like and flag)
1. 
2. 
3. 
(note the icon change for users who accepted in the pair above)
The settings section is visually unchanged 
1. reduction in selector specificity
2. the use of better alignment methods
3. removal of some hardcoded values in favour of core variables
4. replacing all px units with em units
There were a couple of changes to the plugin JS that were necessary.
1. adding markup around some strings for better alignment
2. removal of duplicate classes
3. changes to the toggle logic following number 2 above. …

DEV: CSS refactor and style fixes

---

jobs/scheduled/check_policy.rb

Zeitwerk is failing when we are searching for Jobs::Onceoff, Jobs::Base and Jobs::Scheduled without going back to the top-level namespace (this is correlated to the fact that we got Onceoff base class and module with the same name). 
I noticed that in plugins we are using sometimes :: and sometimes not and that gives me comfort that this change will not break anything.
Travis error: https://travis-ci.org/discourse/discourse/jobs/585072364

[WIP] FIX: Use top-level namespace for base classes

---

app/models/post_policy.rb
db/migrate/20200312233001_add_renew_interval_to_post_policies.rb
jobs/scheduled/check_policy.rb
plugin.rb
spec/lib/check_policy_spec.rb

That feature was described here: https://meta.discourse.org/t/discourse-policy/88557/36
In general, we need an ability to expire policy monthly, quartely an yearly.
To achieve that, the policy is now accepting as `renew` param:
- integer - number of days
- monthly
- quarterly
- yearly

FEATURE: Ability to expire policy monthly, quarterly, yearly

---

jobs/scheduled/check_policy.rb
spec/lib/check_policy_spec.rb

This is so policy reminders do not fall by the wayside. They are given the same priority as bookmark reminder and PM notifications, so they show with the green notification bubble.
Any existing reminder notification will be deleted as well, we don't want the user to end up with tons of duplicate notifications if the policy reminder is aggressive.
**NOTE: The PR https://github.com/discourse/discourse/pull/9660 MUST be merged first!**. I did not want to change _all_ topic reminder notifications to high priority.

UX: When a policy reminder notification is sent mark it as high priority

---

assets/javascripts/lib/discourse-markdown/policy.js.es6

`whiteList` helper is deprecated and should be replaced with `allowList`

FIX: use allowList helper

---

app/controllers/policy_controller.rb
app/models/post_policy.rb
config/locales/server.en.yml
config/settings.yml
spec/requests/policy_controller_spec.rb

The plugin can handle very large groups with recent pages implementation.

DEV: Remove policy_max_group_size site setting

---

assets/javascripts/discourse/components/post-policy.js.es6
assets/javascripts/discourse/templates/components/post-policy.hbs

After accepting or revoking a policy, the other button will be grayed
out and only the selected option will have an icon and color.

UX: Show grey buttons for the other policy option

---

app/controllers/policy_controller.rb
app/models/post_policy.rb
spec/fabricators/post_policy_fabricator.rb
spec/models/post_policy_spec.rb
spec/serializers/post_serializer_spec.rb

Two problems:
1. We were returning suspended users, which we don't really care about when displaying.
2. When returning the first set of 25 users per policy, they were not ordered by ID. The controller that paginates (by an offset of 25) orders users by ID, causing duplicates depending on how the first set was returned.

FIX: Order displayed users and exclude inactive / suspended

---

assets/javascripts/initializers/add-policy-builder.js.es6

Prior to this change editing an existing policy and then creating a new policy would start the builder in editing mode and not insert mode.

FIX: ensures builder state is correctly set

---

spec/models/post_policy_spec.rb

Hardcoding ids inevitably leads to flakes, e.g.
```
2) PostPolicy#accepted_by shows users who accepted ordered by id
Failure/Error: fab!(:policy) { Fabricate(:post_policy, group: group) }
ActiveRecord::RecordNotUnique:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1234) already exists.
```

DEV: Fix flaky specs

---

app/models/post_policy.rb
spec/serializers/post_serializer_spec.rb

We can't use `exists?` method [here](https://github.com/discourse/discourse-policy/blame/8bbd564db11f554565845a2d4d19d8cbb2b7e0be/plugin.rb#L187) if we return an empty array (`[]`). So we're going to use `User.none` method instead.

FIX: Use activerecord's `none` method instead of returning empty array.

---

assets/javascripts/discourse/controllers/policy-builder.js
config/locales/client.en.yml
test/javascripts/acceptance/policy-test.js

When we generate policies via builder we used to include empty policy blocks.
Before builder would insert:
```
[policy ...][/policy]
```
After:
```
[policy ...]
I accept this policy
[/policy]
```

FEATURE: when creating policies, enter canned accept text

---

plugin.rb

Fixes `Required plugin 'discourse_policy' not found` warnings

DEV: Correct the `PLUGIN_NAME`

---

spec/lib/check_policy_spec.rb
spec/lib/pretty_text_spec.rb
spec/models/policy_user_spec.rb

The `#queue_jobs=` method on site settings has been [deprecated](https://github.com/discourse/discourse/commit/1b65469b64e9e569fed67ae11f1dd9ee37702f5c) and replaced by `Jobs.run_later!` and `Jobs.run_immediately!`. This PR replaces usages in this plugin so we can remove the fallback in core.
The fallback used in core for reference:
https://github.com/discourse/discourse/blob/main/app/models/site_setting.rb#L109-L115

DEV: Replace deprecated queue_jobs site setting in tests

---

app/models/post_policy.rb
db/migrate/20231204161807_add_last_bumped_at_to_post_policies.rb
spec/models/post_policy_spec.rb

Currently we have queries to check who hasn’t accepted a policy and when that policy was last triggered for that person.
The problem is that it’s not always reliable as we don’t have a way of knowing when the policy version was bumped for the last time.
This PR adds a new `last_bumped_at` field which will be updated automatically each time the version changes. That way we’ll be able to have more reliable queries.

FEATURE: Track when a policy version is bumped

---

assets/javascripts/lib/discourse-markdown/policy.js
spec/lib/check_policy_spec.rb
spec/lib/pretty_text_spec.rb

Requires https://github.com/discourse/discourse/pull/27173 to be merged.
Will add a `.discourse-compatibility` once merged.

FIX: BBCode parsing specs

---

jobs/scheduled/check_policy.rb

This commit updates the method call on `::DiscoursePolicy::CheckPolicy#missing_users`
to use `find_each` instead of `each`. This avoids loading all the `User`
ActiveRecord models into memory at once when a policy has many missing
users.

PERF: Use `find_each` to avoid memory spikes

---

jobs/scheduled/check_policy.rb

This is a follow up to 9c82f0b08f70824937f642a9c98946f64fae4602 which
applies the same optimisation.

PERF: Use `find_each` to avoid memory spikes take 2

---

db/migrate/20241009155340_alter_post_policy_id_to_bigint.rb

The primary key is usually a bigint column, but the foreign key columns are usually of integer type. This can lead to issues when joining these columns due to mismatched types and different value ranges.

DEV: Fix mismatched column types

---

db/migrate/20190817010201_migrate_post_policy_data.rb
db/migrate/20191014224419_migrate_custom_field_to_policy_users.rb

We are adding the Rails/ReversibleMigrationMethodDefinition cop to rubocop-discourse, this change resolves existing errors under this rule.

DEV: resolve Rails/ReversibleMigrationMethodDefinition errors

---

assets/javascripts/discourse/components/post-policy.gjs

This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.

DEV: Update more deprecated Font Awesome icon names

---

assets/javascripts/discourse/components/post-policy.gjs
lib/extensions/post_serializer_extension.rb
spec/serializers/post_serializer_spec.rb
test/javascripts/integration/components/post-policy-test.gjs

When policy is private, we should only display "no possible users" text for admins.
**Regular user view of public and private policy**
**Admin view of private policy**

FIX: hide "no possible users" when regular user
